version: '3.8'

services:
  ponder:
    build: .
    ports:
      - "${PONDER_PORT:-42069}:42069"  # Ponder GraphQL API
      - "${API_PORT:-3003}:3003"       # REST API wrapper
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PONDER_GRAPHQL_URL=${PONDER_GRAPHQL_URL:-http://localhost:42069/graphql}
      - DATABASE_URL=${DATABASE_URL}
      - ETHEREUM_RPC_URL=${ETHEREUM_RPC_URL}
      - SEPOLIA_RPC_URL=${SEPOLIA_RPC_URL}
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    env_file:
      - .env

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # Remove public port exposure for security
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount initialization scripts that fix permissions
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data: