version: '3.8'

services:
  ponder:
    build: .
    ports:
      - "42069:42069"  # Ponder GraphQL API
      - "3003:3003"    # REST API wrapper
    environment:
      - NODE_ENV=production
      - PONDER_GRAPHQL_URL=http://localhost:42069/graphql
      - DATABASE_URL=postgresql://ponder:ponder@postgres:5432/ponder
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ponder
      POSTGRES_USER: ponder
      POSTGRES_PASSWORD: ponder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: