name: JuiceSwap Ponder DEV CI/CD

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  DOCKER_TAGS: dfxswiss/juiceswap-ponder:beta
  DEPLOY_INFO: ${{ github.ref_name }}-${{ github.sha }}
  AZURE_RESOURCE_GROUP: rg-dfx-api-dev
  AZURE_CONTAINER_APP: ca-dfx-jsp-dev

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test
        continue-on-error: true  # Tests not yet implemented

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_TAGS }}

  deploy:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    environment: development
    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.DFX_DEV_CREDENTIALS }}

      - name: Update Azure Container App
        uses: azure/CLI@v2
        with:
          inlineScript: |
            CURRENT_REVISION=$(az containerapp revision list \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --name ${{ env.AZURE_CONTAINER_APP }} \
              --query "[?properties.active].name" \
              --output tsv | head -1)

            echo "Current active revision: $CURRENT_REVISION"

            az containerapp update \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --name ${{ env.AZURE_CONTAINER_APP }} \
              --image ${{ env.DOCKER_TAGS }} \
              --min-replicas 1 \
              --max-replicas 1 \
              --set-env-vars DEPLOY_INFO=${{ env.DEPLOY_INFO }}

            if [ -n "$CURRENT_REVISION" ]; then
              echo "Deactivating previous revision: $CURRENT_REVISION"
              az containerapp revision deactivate \
                --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
                --name ${{ env.AZURE_CONTAINER_APP }} \
                --revision $CURRENT_REVISION
            else
              echo "No previous revision to deactivate"
            fi

      - name: Logout from Azure
        run: |
          az logout
        if: always()
