name: JuiceSwap Ponder DEV CI/CD

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:
    inputs:
      reset_schema:
        description: 'Create new schema version (resets database)'
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: '20'
  DOCKER_TAGS: dfxswiss/juiceswap-ponder:beta
  DEPLOY_INFO: ${{ github.ref_name }}-${{ github.sha }}
  AZURE_RESOURCE_GROUP: rg-dfx-api-dev
  AZURE_CONTAINER_APP: ca-dfx-jsp-dev

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test
        continue-on-error: true  # Tests not yet implemented

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_TAGS }}

  deploy:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    environment: development
    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.DFX_DEV_CREDENTIALS }}

      - name: Scale down container to prevent conflicts
        uses: azure/CLI@v2
        with:
          inlineScript: |
            echo "Scaling down container app to 0 replicas..."
            az containerapp update \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --name ${{ env.AZURE_CONTAINER_APP }} \
              --min-replicas 0 \
              --max-replicas 0 || echo "Failed to scale down, continuing anyway"
            echo "Waiting 15 seconds for complete shutdown..."
            sleep 15

      - name: Update Azure Container App with new image
        uses: azure/CLI@v2
        with:
          inlineScript: |
            echo "Updating container app with new image and scaling back up..."
            az containerapp update \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --name ${{ env.AZURE_CONTAINER_APP }} \
              --image ${{ env.DOCKER_TAGS }} \
              --min-replicas 1 \
              --max-replicas 1 \
              --set-env-vars DEPLOY_INFO=${{ env.DEPLOY_INFO }}${{ inputs.reset_schema == true && format(' PONDER_SCHEMA_VERSION={0}', github.run_number) || '' }}
            echo "Deployment completed successfully!"

      - name: Logout from Azure
        run: |
          az logout
        if: always()
